<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<RootNamespace>WhatKey</RootNamespace>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ApplicationManifest>app.manifest</ApplicationManifest>
		<ImplicitUsings>enable</ImplicitUsings>
		<RuntimeIdentifiers>win-x64;linux-x64</RuntimeIdentifiers>
		<PublishAot>true</PublishAot>
		<TrimMode>full</TrimMode>
		<OptimizationPreference>Size</OptimizationPreference>
		<InvariantGlobalization>false</InvariantGlobalization>
		<StackTraceSupport>true</StackTraceSupport>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)' == 'Release'">
		<DebugSymbols>false</DebugSymbols>
		<DebugType>None</DebugType>
		<CopyOutputSymbolsToPublishDirectory>false</CopyOutputSymbolsToPublishDirectory>
		<TrimmerRemoveSymbols>true</TrimmerRemoveSymbols>
	</PropertyGroup>

	<ItemGroup>
		<AvaloniaResource Include="Assets\**" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Avalonia" Version="12.1.1" />
		<PackageReference Include="Avalonia.Desktop" Version="12.1.1" />
		<PackageReference Include="Avalonia.Themes.Fluent" Version="12.1.1" />
		<PackageReference Include="ReactiveUI.Avalonia" Version="12.1.1" />
		<PackageReference Include="Microsoft.Extensions.Logging" Version="10.0.1" />
		<PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.1" />
		<PackageReference Include="Serilog" Version="4.4.0" />
		<PackageReference Include="Serilog.Extensions.Logging" Version="9.0.0" />
		<PackageReference Include="Serilog.Sinks.Console" Version="6.1.1" />
		<PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
	</ItemGroup>
</Project>
